const canvasValues = {
  trace: '',
  fill: true,
  stroke: true,
  sizeIncrement: 0,
  initialSize: 0,
  finalSize: 0,
  lineIncrement: 0,
  lineWidth: 0,
  backgroundColor: 0,
  fillColor: 0,
  fillColorChange: 0,
  fillSaturation: 0,
  fillSaturationIncrement: 0,
  fillLightness: 0,
  fillLightnessIncrement: 0,
  strokeColor: 0,
  strokeColorChange: 0,
  strokeSaturation: 0,
  strokeSaturationIncrement: 0,
  strokeLightness: 0,
  strokeLightnessIncrement: 0,
  centerX: 0,
  centerY: 0,
  frames: 0,
  radio: 0,
  radioIncrement: 0,
  angle: 0,
  angleIncrement: 0,
  spiralType: '',
};

export default canvasValues;
